Updated src,naming conventions,comments.Please review.
NitinSaxenait/nitinsaxena_rust_assignment pull request #7
Opened 2021-03-08 19:00 UTC by NitinSaxenait

Please use this PR template
What does this change do?
feature added of complex number and student operations
Any additional information for the reviewer to start
NA

How should this be manually tested?
We need window OS in which Rust is installed. then execute this rust program

Which Trello task and sub-task does this change relate to?

Are there any changes pending?
No

Does any team have to be notified of changes in this feature?
No, only for the mentor.

Definition of Done:

Is there >80% unit test code coverage?
if not please mention the Code Coverage of code.

code coverage:
src/complex_number.rs 14/14
src/student_score.rs 16/34
src/test.rs: 29/29
76.62% coverage , 59/77

Does this PR add new dependencies? If so, please list out the same.
No

Will this feature require a new piece of infrastructure to be implemented?
Is there appropriate logging included?
yes
Does the project compile ok?
yes

Have Clippy violations been fixed?
yes

Have Code is properly formatted?
yes

2021-03-09 10:19 UTC, Dheerajjnv reviewed
Remove the deleted file as it already pushed.

2021-03-09 10:19 UTC, Dheerajjnv commented on Assignments/assignment5/src/complex_number.rs
> +impl ComplexNumbers {
Return self instead of string.

2021-03-09 10:19 UTC, Dheerajjnv commented on Assignments/assignment5/src/student_score.rs
> +    pub(crate) hindi: i32,
Remove crate

2021-03-09 10:19 UTC, Dheerajjnv commented on Assignments/assignment5/src/student_score.rs
> +    pub fn compare_student(&self, second_student: &Score) {
Pass the Other student instead of the score.

2021-03-14 15:05 UTC, Dheerajjnv requested changes
Remove Deleted file.

2021-03-14 15:05 UTC, Dheerajjnv commented on Assignments/assignment5/src/student_score.rs
> +    pub(crate) score_of_each_subject: Score,
No need of crate.

2021-03-14 15:05 UTC, Dheerajjnv commented on Assignments/assignment5/src/test.rs
> +    let mut pass_check_test = StudentInformation::new(&student1_marks);
Pass student as a parameter

2021-03-14 15:06 UTC, sonukumar-a11 approved these changes
please remove the unwanted file in the git

2021-03-14 16:07 UTC, closed without merging